# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ./d008.h
SOURCES += ./d008.cpp \
    ./main.cpp
FORMS += ./d008.ui
RESOURCES += d008.qrc
